import re
import glob

def normalize(text):
    return re.sub(r'[^a-zA-Z0-9]', '', text.lower())

headers = [
"Neurones: Types and Functions",
"How a Response is Generated by Effectors",
"The Reflex Arc",
"The Nerve Impulse",
"Myelination & Saltatory Conduction",
"Synapses & Neurotransmitters",
"The Effects of Drugs on Nervous Transmission",
"Detection of Stimuli",
"Habituation",
"Central & Peripheral Nervous System"
]

js_contents = ""
for jf in glob.glob('src/data/seedNotes/biology/*.js'):
    with open(jf, 'r', encoding='utf-8') as f:
        js_contents += f.read()

normalized_js = normalize(js_contents)

for h in headers:
    if normalize(h) not in normalized_js:
        print(f"Missing: {h}")
