import json

with open('nervous.txt', 'r', encoding='utf-8') as f:
    text = f.read()

# Define boundaries for topics based on the contents
bounds = {
    '0': text.find('\nNeurones: Types & Functions'),
    '0b': text.find('\nHow a Response is Generated by Effectors'),
    '0c': text.find('\nThe Reflex Arc'),
    '1': text.find('\nThe Nerve Impulse'),
    '2': text.find('\nMyelination & Saltatory Conduction'),
    '3': text.find('\nSynapses & Neurotransmitters'),
    '4': text.find('\nThe Effects of Drugs on Nervous Transmission'),
    '5': text.find('\nDetection of Stimuli'),
    '8': text.find('\nHabituation\n'),
    '15': text.find('\nCentral & Peripheral Nervous System'),
    'end': len(text)
}

print("Bounds keys and found indices:")
for k, v in bounds.items():
    print(f"{k}: {v}")

