import json

with open('nervous.txt', 'r', encoding='utf-8') as f:
    text = f.read()

bounds = {
    '0': text.find('\nNeurones: Types and Functions'),
    '0b': text.find('\nHow a Response is Generated by Effectors', 1000),
    '0c': text.find('\nThe Reflex Arc', 1000),
    '1': text.find('\nThe Nerve Impulse', 1000),
    '2': text.find('\nMyelination & Saltatory Conduction', 1000),
    '3': text.find('\nSynapses & Neurotransmitters', 1000),
    '4': text.find('\nThe Effects of Drugs on Nervous Transmission', 1000),
    '5': text.find('\nDetection of Stimuli', 1000),
    '8': text.find('\nHabituation\n', 1000),
    '15': text.find('\nCentral & Peripheral Nervous System', 1000),
    'end': len(text)
}

# 5_8_0
c0 = text[bounds['0']:bounds['1']]
c1 = text[bounds['1']:bounds['2']]
c2 = text[bounds['2']:bounds['3']]
c3 = text[bounds['3']:bounds['4']]
c4 = text[bounds['4']:bounds['5']]
c5 = text[bounds['5']:bounds['8']]
c8 = text[bounds['8']:bounds['15']]
c15 = text[bounds['15']:bounds['end']]

out = {
    '0': c0,
    '1': c1,
    '2': c2,
    '3': c3,
    '4': c4,
    '5': c5,
    '8': c8,
    '15': c15
}

def process_text_to_blocks(subtopic_id, content):
    lines = content.split('\n')
    blocks = []
    
    blocks.append({
        'id': f'obj_{subtopic_id}',
        'type': 'objective',
        'data': { 'text': 'Understand the key concepts of this section according to the Edexcel IAL Biology syllabus.' }
    })
    
    current_para = []
    for line in lines:
        cleaned = line.strip()
        if not cleaned: continue
        if 'Save My Exams' in cleaned or 'Your notes' in cleaned or 'Edexcel International A' in cleaned or 'Level (IAL) Biology' in cleaned or 'Table' in cleaned or 'Contents' in cleaned:
            continue
            
        if len(cleaned) < 100 and not cleaned.endswith('.') and not cleaned.endswith(',') and not cleaned.startswith('(') and not cleaned.endswith(')'):
            if current_para:
                blocks.append({
                    'id': f'p_{subtopic_id}_{len(blocks)}',
                    'type': 'paragraph',
                    'data': { 'text': ' '.join(current_para) }
                })
                current_para = []
            
            blocks.append({
                'id': f'h_{subtopic_id}_{len(blocks)}',
                'type': 'heading',
                'data': { 'text': cleaned, 'level': 3 }
            })
        else:
            current_para.append(cleaned)
            
    if current_para:
        blocks.append({
            'id': f'p_{subtopic_id}_{len(blocks)}',
            'type': 'paragraph',
            'data': { 'text': ' '.join(current_para) }
        })

    json_blocks = json.dumps(blocks, indent=4)
    return f'export const note_biology_5_8_{subtopic_id} = {{\n  blocks: {json_blocks}\n}};\n'

for key, content in out.items():
    js_code = process_text_to_blocks(key, content)
    with open(f'src/data/seedNotes/biology/note_5_8_{key}.js', 'w', encoding='utf-8') as f:
        f.write(js_code)
    print(f'Populated note_5_8_{key}.js length {len(js_code)}')
