// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import DeleteFlashcardReducer from "../delete_flashcard_reducer";
import DeleteNoteReducer from "../delete_note_reducer";
import DeleteNoteAssetReducer from "../delete_note_asset_reducer";
import RegisterUserReducer from "../register_user_reducer";
import SaveFlashcardReducer from "../save_flashcard_reducer";
import SaveNoteAssetReducer from "../save_note_asset_reducer";
import UpsertNoteReducer from "../upsert_note_reducer";

export type DeleteFlashcardParams = __Infer<typeof DeleteFlashcardReducer>;
export type DeleteNoteParams = __Infer<typeof DeleteNoteReducer>;
export type DeleteNoteAssetParams = __Infer<typeof DeleteNoteAssetReducer>;
export type RegisterUserParams = __Infer<typeof RegisterUserReducer>;
export type SaveFlashcardParams = __Infer<typeof SaveFlashcardReducer>;
export type SaveNoteAssetParams = __Infer<typeof SaveNoteAssetReducer>;
export type UpsertNoteParams = __Infer<typeof UpsertNoteReducer>;

