// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  cardId: __t.string().primaryKey().name("card_id"),
  ownerIdentity: __t.identity().name("owner_identity"),
  subject: __t.string(),
  sourceNoteId: __t.string().name("source_note_id"),
  sourceLabel: __t.string().name("source_label"),
  front: __t.string(),
  back: __t.string(),
  createdAt: __t.u64().name("created_at"),
});
