// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 2.0.2 (commit bc4fcec6f33f607fb46f61ae66c479eecf5a6e74).

/* eslint-disable */
/* tslint:disable */
import {
  DbConnectionBuilder as __DbConnectionBuilder,
  DbConnectionImpl as __DbConnectionImpl,
  SubscriptionBuilderImpl as __SubscriptionBuilderImpl,
  TypeBuilder as __TypeBuilder,
  Uuid as __Uuid,
  convertToAccessorMap as __convertToAccessorMap,
  makeQueryBuilder as __makeQueryBuilder,
  procedureSchema as __procedureSchema,
  procedures as __procedures,
  reducerSchema as __reducerSchema,
  reducers as __reducers,
  schema as __schema,
  t as __t,
  table as __table,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type DbConnectionConfig as __DbConnectionConfig,
  type ErrorContextInterface as __ErrorContextInterface,
  type Event as __Event,
  type EventContextInterface as __EventContextInterface,
  type Infer as __Infer,
  type QueryBuilder as __QueryBuilder,
  type ReducerEventContextInterface as __ReducerEventContextInterface,
  type RemoteModule as __RemoteModule,
  type SubscriptionEventContextInterface as __SubscriptionEventContextInterface,
  type SubscriptionHandleImpl as __SubscriptionHandleImpl,
} from "spacetimedb";

// Import all reducer arg schemas
import DeleteFlashcardReducer from "./delete_flashcard_reducer";
import DeleteNoteReducer from "./delete_note_reducer";
import DeleteNoteAssetReducer from "./delete_note_asset_reducer";
import RegisterUserReducer from "./register_user_reducer";
import SaveFlashcardReducer from "./save_flashcard_reducer";
import SaveNoteAssetReducer from "./save_note_asset_reducer";
import UpsertNoteReducer from "./upsert_note_reducer";
import CreateLiveSessionReducer from "./create_live_session_reducer";
import JoinSessionReducer from "./join_session_reducer";
import InviteToSessionReducer from "./invite_to_session_reducer";
import RespondToInviteReducer from "./respond_to_invite_reducer";
import AddStrokeReducer from "./add_stroke_reducer";
import UpdateStrokeReducer from "./update_stroke_reducer";
import DeleteStrokeReducer from "./delete_stroke_reducer";
import EndSessionReducer from "./end_session_reducer";
import SetTeacherRoleReducer from "./set_teacher_role_reducer";
import CreateLiveClassReducer from "./create_live_class_reducer";
import JoinLiveClassReducer from "./join_live_class_reducer";
import EndLiveClassReducer from "./end_live_class_reducer";
import SetBackgroundReducer from "./set_background_reducer";
import UpdateCursorReducer from "./update_cursor_reducer";
import RaiseHandReducer from "./raise_hand_reducer";
import AcknowledgeHandRaiseReducer from "./acknowledge_hand_raise_reducer";
import UpdateClassTimerReducer from "./update_class_timer_reducer";

// Import all procedure arg schemas

// Import all table schema definitions
import FlashcardRow from "./flashcard_table";
import NoteRow from "./note_table";
import NoteAssetRow from "./note_asset_table";
import UserRow from "./user_table";
import LiveSessionRow from "./live_session_table";
import SessionParticipantRow from "./session_participant_table";
import AnnotationStrokeRow from "./annotation_stroke_table";
import SessionInviteRow from "./session_invite_table";
import LiveClassSessionRow from "./live_class_session_table";
import LiveClassCursorRow from "./live_class_cursor_table";
import HandRaiseRow from "./hand_raise_table";
import ClassTimerRow from "./class_timer_table";

/** Type-only namespace exports for generated type groups. */

/** The schema information for all tables in this module. This is defined the same was as the tables would have been defined in the server. */
const tablesSchema = __schema({
  flashcard: __table({
    name: 'flashcard',
    indexes: [
      { name: 'card_id', algorithm: 'btree', columns: [
        'cardId',
      ] },
    ],
    constraints: [
      { name: 'flashcard_card_id_key', constraint: 'unique', columns: ['cardId'] },
    ],
  }, FlashcardRow),
  note: __table({
    name: 'note',
    indexes: [
      { name: 'note_id', algorithm: 'btree', columns: [
        'noteId',
      ] },
    ],
    constraints: [
      { name: 'note_note_id_key', constraint: 'unique', columns: ['noteId'] },
    ],
  }, NoteRow),
  note_asset: __table({
    name: 'note_asset',
    indexes: [
      { name: 'asset_id', algorithm: 'btree', columns: [
        'assetId',
      ] },
    ],
    constraints: [
      { name: 'note_asset_asset_id_key', constraint: 'unique', columns: ['assetId'] },
    ],
  }, NoteAssetRow),
  user: __table({
    name: 'user',
    indexes: [
      { name: 'identity', algorithm: 'btree', columns: [
        'identity',
      ] },
    ],
    constraints: [
      { name: 'user_identity_key', constraint: 'unique', columns: ['identity'] },
    ],
  }, UserRow),
  live_session: __table({
    name: 'live_session',
    indexes: [
      { name: 'session_id', algorithm: 'btree', columns: ['sessionId'] },
    ],
    constraints: [
      { name: 'live_session_session_id_key', constraint: 'unique', columns: ['sessionId'] },
    ],
  }, LiveSessionRow),
  session_participant: __table({
    name: 'session_participant',
    indexes: [
      { name: 'participant_id', algorithm: 'btree', columns: ['participantId'] },
    ],
    constraints: [
      { name: 'session_participant_participant_id_key', constraint: 'unique', columns: ['participantId'] },
    ],
  }, SessionParticipantRow),
  annotation_stroke: __table({
    name: 'annotation_stroke',
    indexes: [
      { name: 'stroke_id', algorithm: 'btree', columns: ['strokeId'] },
    ],
    constraints: [
      { name: 'annotation_stroke_stroke_id_key', constraint: 'unique', columns: ['strokeId'] },
    ],
  }, AnnotationStrokeRow),
  session_invite: __table({
    name: 'session_invite',
    indexes: [
      { name: 'invite_id', algorithm: 'btree', columns: ['inviteId'] },
    ],
    constraints: [
      { name: 'session_invite_invite_id_key', constraint: 'unique', columns: ['inviteId'] },
    ],
  }, SessionInviteRow),
  live_class_session: __table({
    name: 'live_class_session',
    indexes: [
      { name: 'class_id', algorithm: 'btree', columns: ['classId'] },
    ],
    constraints: [
      { name: 'live_class_session_class_id_key', constraint: 'unique', columns: ['classId'] },
    ],
  }, LiveClassSessionRow),
  live_class_cursor: __table({
    name: 'live_class_cursor',
    indexes: [
      { name: 'cursor_id', algorithm: 'btree', columns: ['cursorId'] },
    ],
    constraints: [
      { name: 'live_class_cursor_cursor_id_key', constraint: 'unique', columns: ['cursorId'] },
    ],
  }, LiveClassCursorRow),
  hand_raise: __table({
    name: 'hand_raise',
    indexes: [
      { name: 'raise_id', algorithm: 'btree', columns: ['raiseId'] },
    ],
    constraints: [
      { name: 'hand_raise_raise_id_key', constraint: 'unique', columns: ['raiseId'] },
    ],
  }, HandRaiseRow),
  class_timer: __table({
    name: 'class_timer',
    indexes: [
      { name: 'class_id', algorithm: 'btree', columns: ['classId'] },
    ],
    constraints: [
      { name: 'class_timer_class_id_key', constraint: 'unique', columns: ['classId'] },
    ],
  }, ClassTimerRow),
});

/** The schema information for all reducers in this module. This is defined the same way as the reducers would have been defined in the server, except the body of the reducer is omitted in code generation. */
const reducersSchema = __reducers(
  __reducerSchema("delete_flashcard", DeleteFlashcardReducer),
  __reducerSchema("delete_note", DeleteNoteReducer),
  __reducerSchema("delete_note_asset", DeleteNoteAssetReducer),
  __reducerSchema("register_user", RegisterUserReducer),
  __reducerSchema("save_flashcard", SaveFlashcardReducer),
  __reducerSchema("save_note_asset", SaveNoteAssetReducer),
  __reducerSchema("upsert_note", UpsertNoteReducer),
  __reducerSchema("create_live_session", CreateLiveSessionReducer),
  __reducerSchema("join_session", JoinSessionReducer),
  __reducerSchema("invite_to_session", InviteToSessionReducer),
  __reducerSchema("respond_to_invite", RespondToInviteReducer),
  __reducerSchema("add_stroke", AddStrokeReducer),
  __reducerSchema("update_stroke", UpdateStrokeReducer),
  __reducerSchema("delete_stroke", DeleteStrokeReducer),
  __reducerSchema("end_session", EndSessionReducer),
  __reducerSchema("set_teacher_role", SetTeacherRoleReducer),
  __reducerSchema("create_live_class", CreateLiveClassReducer),
  __reducerSchema("join_live_class", JoinLiveClassReducer),
  __reducerSchema("end_live_class", EndLiveClassReducer),
  __reducerSchema("set_background", SetBackgroundReducer),
  __reducerSchema("update_cursor", UpdateCursorReducer),
  __reducerSchema("raise_hand", RaiseHandReducer),
  __reducerSchema("acknowledge_hand_raise", AcknowledgeHandRaiseReducer),
  __reducerSchema("update_class_timer", UpdateClassTimerReducer),
);

/** The schema information for all procedures in this module. This is defined the same way as the procedures would have been defined in the server. */
const proceduresSchema = __procedures(
);

/** The remote SpacetimeDB module schema, both runtime and type information. */
const REMOTE_MODULE = {
  versionInfo: {
    cliVersion: "2.0.2" as const,
  },
  tables: tablesSchema.schemaType.tables,
  reducers: reducersSchema.reducersType.reducers,
  ...proceduresSchema,
} satisfies __RemoteModule<
  typeof tablesSchema.schemaType,
  typeof reducersSchema.reducersType,
  typeof proceduresSchema
>;

/** The tables available in this remote SpacetimeDB module. Each table reference doubles as a query builder. */
export const tables: __QueryBuilder<typeof tablesSchema.schemaType> = __makeQueryBuilder(tablesSchema.schemaType);

/** The reducers available in this remote SpacetimeDB module. */
export const reducers = __convertToAccessorMap(reducersSchema.reducersType.reducers);

/** The context type returned in callbacks for all possible events. */
export type EventContext = __EventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for reducer events. */
export type ReducerEventContext = __ReducerEventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for subscription events. */
export type SubscriptionEventContext = __SubscriptionEventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for error events. */
export type ErrorContext = __ErrorContextInterface<typeof REMOTE_MODULE>;
/** The subscription handle type to manage active subscriptions created from a {@link SubscriptionBuilder}. */
export type SubscriptionHandle = __SubscriptionHandleImpl<typeof REMOTE_MODULE>;

/** Builder class to configure a new subscription to the remote SpacetimeDB instance. */
export class SubscriptionBuilder extends __SubscriptionBuilderImpl<typeof REMOTE_MODULE> {}

/** Builder class to configure a new database connection to the remote SpacetimeDB instance. */
export class DbConnectionBuilder extends __DbConnectionBuilder<DbConnection> {}

/** The typed database connection to manage connections to the remote SpacetimeDB instance. This class has type information specific to the generated module. */
export class DbConnection extends __DbConnectionImpl<typeof REMOTE_MODULE> {
  /** Creates a new {@link DbConnectionBuilder} to configure and connect to the remote SpacetimeDB instance. */
  static builder = (): DbConnectionBuilder => {
    return new DbConnectionBuilder(REMOTE_MODULE, (config: __DbConnectionConfig<typeof REMOTE_MODULE>) => new DbConnection(config));
  };

  /** Creates a new {@link SubscriptionBuilder} to configure a subscription to the remote SpacetimeDB instance. */
  override subscriptionBuilder = (): SubscriptionBuilder => {
    return new SubscriptionBuilder(this);
  };
}

