// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  assetId: __t.string().primaryKey().name("asset_id"),
  noteId: __t.string().name("note_id"),
  ownerIdentity: __t.identity().name("owner_identity"),
  assetType: __t.string().name("asset_type"),
  data: __t.string(),
  createdAt: __t.u64().name("created_at"),
});
