// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  noteId: __t.string().primaryKey().name("note_id"),
  ownerIdentity: __t.identity().name("owner_identity"),
  subject: __t.string(),
  title: __t.string(),
  subtopicTitle: __t.string().name("subtopic_title"),
  breadcrumbs: __t.string(),
  contentJson: __t.string().name("content_json"),
  confidenceScore: __t.u8().name("confidence_score"),
  estimatedReadMinutes: __t.u32().name("estimated_read_minutes"),
  createdAt: __t.u64().name("created_at"),
  lastEditedAt: __t.u64().name("last_edited_at"),
});
