// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const Flashcard = __t.object("Flashcard", {
  cardId: __t.string(),
  ownerIdentity: __t.identity(),
  subject: __t.string(),
  sourceNoteId: __t.string(),
  sourceLabel: __t.string(),
  front: __t.string(),
  back: __t.string(),
  createdAt: __t.u64(),
});
export type Flashcard = __Infer<typeof Flashcard>;

export const Note = __t.object("Note", {
  noteId: __t.string(),
  ownerIdentity: __t.identity(),
  subject: __t.string(),
  title: __t.string(),
  subtopicTitle: __t.string(),
  breadcrumbs: __t.string(),
  contentJson: __t.string(),
  confidenceScore: __t.u8(),
  estimatedReadMinutes: __t.u32(),
  createdAt: __t.u64(),
  lastEditedAt: __t.u64(),
});
export type Note = __Infer<typeof Note>;

export const NoteAsset = __t.object("NoteAsset", {
  assetId: __t.string(),
  noteId: __t.string(),
  ownerIdentity: __t.identity(),
  assetType: __t.string(),
  data: __t.string(),
  createdAt: __t.u64(),
});
export type NoteAsset = __Infer<typeof NoteAsset>;

export const User = __t.object("User", {
  identity: __t.identity(),
  username: __t.string(),
  createdAt: __t.u64(),
  role: __t.string(),
});
export type User = __Infer<typeof User>;

export const LiveClassSession = __t.object("LiveClassSession", {
  classId: __t.u64(),
  hostIdentity: __t.identity(),
  title: __t.string(),
  backgroundType: __t.string(),
  status: __t.string(),
  createdAt: __t.u64(),
});
export type LiveClassSession = __Infer<typeof LiveClassSession>;

export const LiveClassCursor = __t.object("LiveClassCursor", {
  cursorId: __t.identity(),
  classId: __t.u64(),
  x: __t.f32(),
  y: __t.f32(),
  tool: __t.string(),
  mode: __t.string(),
  updatedAt: __t.u64(),
});
export type LiveClassCursor = __Infer<typeof LiveClassCursor>;

export const ClassTimer = __t.object("ClassTimer", {
  classId: __t.u64(),
  mode: __t.string(),
  state: __t.string(),
  elapsedMs: __t.u64(),
  targetMs: __t.u64(),
  startedAt: __t.u64(),
});
export type ClassTimer = __Infer<typeof ClassTimer>;

export const HandRaise = __t.object("HandRaise", {
  raiseId: __t.u64(),
  classId: __t.u64(),
  studentIdentity: __t.identity(),
  status: __t.string(),
  raisedAt: __t.u64(),
});
export type HandRaise = __Infer<typeof HandRaise>;

export const AnnotationStroke = __t.object("AnnotationStroke", {
  strokeId: __t.u64(),
  sessionId: __t.u64(),
  pageNumber: __t.u32(),
  userIdentity: __t.identity(),
  fabricObjectJson: __t.string(),
  createdAt: __t.u64(),
  updatedAt: __t.u64(),
});
export type AnnotationStroke = __Infer<typeof AnnotationStroke>;

export const LiveSession = __t.object("LiveSession", {
  sessionId: __t.u64(),
  hostIdentity: __t.identity(),
  paperId: __t.string(),
  title: __t.string(),
  status: __t.string(),
  createdAt: __t.u64(),
});
export type LiveSession = __Infer<typeof LiveSession>;

export const SessionParticipant = __t.object("SessionParticipant", {
  participantId: __t.u64(),
  sessionId: __t.u64(),
  userIdentity: __t.identity(),
  role: __t.string(),
  joinedAt: __t.u64(),
});
export type SessionParticipant = __Infer<typeof SessionParticipant>;

export const SessionInvite = __t.object("SessionInvite", {
  inviteId: __t.u64(),
  sessionId: __t.u64(),
  fromIdentity: __t.identity(),
  toUsername: __t.string(),
  status: __t.string(),
  createdAt: __t.u64(),
});
export type SessionInvite = __Infer<typeof SessionInvite>;

