// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const Flashcard = __t.object("Flashcard", {
  cardId: __t.string(),
  ownerIdentity: __t.identity(),
  subject: __t.string(),
  sourceNoteId: __t.string(),
  sourceLabel: __t.string(),
  front: __t.string(),
  back: __t.string(),
  createdAt: __t.u64(),
});
export type Flashcard = __Infer<typeof Flashcard>;

export const Note = __t.object("Note", {
  noteId: __t.string(),
  ownerIdentity: __t.identity(),
  subject: __t.string(),
  title: __t.string(),
  subtopicTitle: __t.string(),
  breadcrumbs: __t.string(),
  contentJson: __t.string(),
  confidenceScore: __t.u8(),
  estimatedReadMinutes: __t.u32(),
  createdAt: __t.u64(),
  lastEditedAt: __t.u64(),
});
export type Note = __Infer<typeof Note>;

export const NoteAsset = __t.object("NoteAsset", {
  assetId: __t.string(),
  noteId: __t.string(),
  ownerIdentity: __t.identity(),
  assetType: __t.string(),
  data: __t.string(),
  createdAt: __t.u64(),
});
export type NoteAsset = __Infer<typeof NoteAsset>;

export const User = __t.object("User", {
  identity: __t.identity(),
  username: __t.string(),
  createdAt: __t.u64(),
});
export type User = __Infer<typeof User>;

